import type { Signal } from '@/types/signal';

export const mockSignals: Signal[] = [
  {
    id: '1',
    pair: 'BTC/USD',
    type: 'BUY',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    entry: 68500.0,
    takeProfit: 69500.0,
    stopLoss: 68000.0,
    rationale: 'Strong bullish momentum detected on the 4H chart, breaking past a key resistance level. RSI indicates room for further growth before being overbought.',
  },
  {
    id: '2',
    pair: 'ETH/USD',
    type: 'SELL',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 25),
    entry: 3600.0,
    takeProfit: 3500.0,
    stopLoss: 3650.0,
    rationale: 'Formation of a bearish divergence on the daily chart, coupled with increasing volume on down-moves. Price is currently testing upper Bollinger Band.',
  },
  {
    id: '3',
    pair: 'SOL/USD',
    type: 'BUY',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    entry: 165.5,
    takeProfit: 175.0,
    stopLoss: 160.0,
    rationale: 'A golden cross pattern is forming on the 6H chart. The ecosystem has seen positive news flow, suggesting a potential short-term rally.',
  },
  {
    id: '4',
    pair: 'XRP/USD',
    type: 'BUY',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 75),
    entry: 0.52,
    takeProfit: 0.58,
    stopLoss: 0.49,
    rationale: 'Price has found strong support at the $0.50 level and is showing signs of reversal. MACD histogram is turning positive.',
  },
  {
    id: '5',
    pair: 'ADA/USD',
    type: 'SELL',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    entry: 0.45,
    takeProfit: 0.42,
    stopLoss: 0.47,
    rationale: 'Price has been rejected at the 50-day moving average. A death cross is imminent on the daily timeframe, indicating potential for further downside.',
  },
    {
    id: '6',
    pair: 'BTC/USD',
    type: 'SELL',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    entry: 69200.0,
    takeProfit: 68200.0,
    stopLoss: 69700.0,
    rationale: 'Double top formation visible on the 1H chart, indicating a potential short-term pullback. High selling pressure observed at the $69.5k resistance zone.',
  },
  {
    id: '7',
    pair: 'ETH/USD',
    type: 'BUY',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 240),
    entry: 3550.0,
    takeProfit: 3650.0,
    stopLoss: 3500.0,
    rationale: 'Bouncing off a critical support level that aligns with the 0.618 Fibonacci retracement. Increasing institutional interest suggests upside potential.',
  },
  {
    id: '8',
    pair: 'SOL/USD',
    type: 'SELL',
    category: 'Crypto',
    timestamp: new Date(Date.now() - 1000 * 60 * 300),
    entry: 170.0,
    takeProfit: 160.0,
    stopLoss: 175.0,
    rationale: 'Overbought conditions on the RSI across multiple timeframes. Profit-taking is expected after a significant recent rally, leading to a corrective move.',
  },
  {
    id: '9',
    pair: 'NAS100/USD',
    type: 'BUY',
    category: 'Stock Indices',
    timestamp: new Date(Date.now() - 1000 * 60 * 320),
    entry: 19600.0,
    takeProfit: 19800.0,
    stopLoss: 19500.0,
    rationale: 'Strong quarterly earnings from tech giants are driving the index higher. Bullish engulfing candle on the daily chart.',
  },
  {
    id: '10',
    pair: 'US30/USD',
    type: 'SELL',
    category: 'Stock Indices',
    timestamp: new Date(Date.now() - 1000 * 60 * 360),
    entry: 39100.0,
    takeProfit: 38800.0,
    stopLoss: 39250.0,
    rationale: 'Weak manufacturing data and concerns over inflation are creating bearish pressure. The index is facing resistance at the 20-day EMA.',
  },
  {
    id: '11',
    pair: 'EUR/USD',
    type: 'BUY',
    category: 'Forex',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    entry: 1.0720,
    takeProfit: 1.0780,
    stopLoss: 1.0690,
    rationale: 'Anticipation of positive economic data from the Eurozone. Price is showing a bullish engulfing pattern on the 4H chart.',
  },
  {
    id: '12',
    pair: 'XAU/USD',
    type: 'SELL',
    category: 'Metals',
    timestamp: new Date(Date.now() - 1000 * 60 * 55),
    entry: 2350.0,
    takeProfit: 2320.0,
    stopLoss: 2365.0,
    rationale: 'Gold is facing strong resistance at the $2360 level. A stronger dollar is adding pressure on commodity prices.',
  },
  {
    id: '13',
    pair: 'VIX',
    type: 'BUY',
    category: 'Volatility Indices',
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    entry: 13.5,
    takeProfit: 15.0,
    stopLoss: 12.8,
    rationale: 'Increasing market uncertainty ahead of the central bank announcements. A spike in volatility is expected.',
  },
  {
    id: '14',
    pair: 'GBP/JPY',
    type: 'SELL',
    category: 'Forex',
    timestamp: new Date(Date.now() - 1000 * 60 * 140),
    entry: 201.50,
    takeProfit: 200.00,
    stopLoss: 202.25,
    rationale: 'Bearish divergence on the RSI suggests a potential reversal from the recent highs. The pair is overextended.',
  }
];
